// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/it00021hot/gen-admin/internal/app/tool/dao/internal"
)

// genDatabaseDao is the data access object for table gen_database.
// You can define custom methods on it to extend its functionality as you wish.
type genDatabaseDao struct {
	*internal.GenDatabaseDao
}

var (
	// GenDatabase is globally public accessible object for table gen_database operations.
	GenDatabase = genDatabaseDao{
		internal.NewGenDatabaseDao(),
	}
)

// Fill with you ideas below.
