// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/it00021hot/gen-admin/internal/app/tool/logic/database"
	_ "github.com/it00021hot/gen-admin/internal/app/tool/logic/table"
	_ "github.com/it00021hot/gen-admin/internal/app/tool/logic/table_column"
	_ "github.com/it00021hot/gen-admin/internal/app/tool/logic/template"
)
