// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GenTableColumn is the golang structure for table gen_table_column.
type GenTableColumn struct {
	ColumnId      int64       `json:"columnId"     dc:"编号"`                             //
	TableId       int64       `json:"tableId"      dc:"归属表编号"`                          //
	ColumnName    string      `json:"columnName"   dc:"列名称"`                            //
	ColumnComment string      `json:"columnComment"dc:"列描述"`                            //
	ColumnType    string      `json:"columnType"   dc:"列类型"`                            //
	ColumnLength  int         `json:"columnLength" dc:"列长度"`                            //
	JavaType      string      `json:"javaType"     dc:"JAVA类型"`                         //
	JavaField     string      `json:"javaField"    dc:"JAVA字段名"`                        //
	GoType        string      `json:"goType"       dc:"GO类型"`                           //
	GoField       string      `json:"goField"      dc:"GO字段名"`                          //
	TsType        string      `json:"tsType" 	   dc:"ts类型"`                             //ts类型
	TsField       string      `json:"tsField"      dc:"ts字段"`                           //ts字段
	IsPk          bool        `json:"isPk"         dc:"是否主键（1是）"`                       //
	IsIncrement   bool        `json:"isIncrement"  dc:"是否自增（1是）"`                       //
	IsRequired    bool        `json:"isRequired"   dc:"是否必填（1是）"`                       //
	IsInsert      bool        `json:"isInsert"     dc:"是否为插入字段（1是）"`                    //
	IsEdit        bool        `json:"isEdit"       dc:"是否编辑字段（1是）"`                     //
	IsList        bool        `json:"isList"       dc:"是否列表字段（1是）"`                     //
	IsQuery       bool        `json:"isQuery"      dc:"是否查询字段（1是）"`                     //
	QueryType     string      `json:"queryType"    dc:"查询方式（等于、不等于、大于、小于、范围）"`          //
	HtmlType      string      `json:"htmlType"     dc:"显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）"` //
	DictType      string      `json:"dictType"     dc:"字典类型"`                           //
	Sort          int         `json:"sort"         dc:"排序"`                             //
	CreateBy      string      `json:"createBy"     dc:"创建者"`                            //
	CreateTime    *gtime.Time `json:"createTime"   dc:"创建时间"`                           //
	UpdateBy      string      `json:"updateBy"     dc:"更新者"`                            //
	UpdateTime    *gtime.Time `json:"updateTime"   dc:"更新时间"`                           //
}
