// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GenTable is the golang structure for table gen_table.
type GenTable struct {
	TableId        int64       `json:"tableId"        ` // 编号
	TableName      string      `json:"tableName"      ` // 表名称
	TableComment   string      `json:"tableComment"   ` // 表描述
	TplCategory    string      `json:"tplCategory"    ` // 使用的模板（crud单表操作 tree树表操作 sub主子表操作）
	SubTableName   string      `json:"subTableName"   ` // 关联子表的表名
	SubTableFkName string      `json:"subTableFkName" ` // 子表关联的外键名
	TreeCode       string      `json:"treeCode"       ` // 树编码字段
	TreeName       string      `json:"treeName"       ` // 树编码字段
	TreeParentCode string      `json:"treeParentCode" ` // 树编码字段
	ClassName      string      `json:"className"      ` // 实体类名称
	SystemName     string      `json:"systemName"     ` // 系统名称
	ModuleName     string      `json:"moduleName"     ` // 生成模块名
	PackageName    string      `json:"packageName"    ` // 生成包路径
	BusinessName   string      `json:"businessName"   ` // 生成业务名
	FunctionName   string      `json:"functionName"   ` // 生成功能名
	FunctionAuthor string      `json:"functionAuthor" ` // 生成功能作者
	GenType        string      `json:"genType"        ` // 生成代码方式（0zip压缩包 1自定义路径）
	GenPath        string      `json:"genPath"        ` // 生成路径（不填默认项目路径）
	Params         string      `json:"params"         ` // 额外属性
	CreateBy       string      `json:"createBy"       ` // 创建者
	CreateTime     *gtime.Time `json:"createTime"     ` // 创建时间
	UpdateBy       string      `json:"updateBy"       ` // 更新者
	UpdateTime     *gtime.Time `json:"updateTime"     ` // 更新时间
	Remark         string      `json:"remark"         ` // 备注
}
