apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: mysql-client
  name: mysql-client
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 120
  template:
    metadata:
      name: mysql-client
      labels:
        app.kubernetes.io/name: mysql-client
    spec:
      initContainers:
        - name: mysql-check
          image: registry.cn-shanghai.aliyuncs.com/c7n/mysql-client:10.4.13
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          args:
            - -c
            - $(while ! mysqlcheck --host="${MYSQL_HOST}" --port="${MYSQL_PORT}" --user="${MYSQL_USER}" --password="${MYSQL_PASS}" information_schema; do sleep 1; done)
          command:
            - /bin/sh
      containers:
        - name: mysql-client
          image: registry.cn-shanghai.aliyuncs.com/c7n/mysql-client:10.4.13
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: SQL_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: init-sql
                  key: gen-admin.sql
          args:
            - -c
            - $(mysql -u"${MYSQL_USER}" -p"${MYSQL_PASS}" -h"${MYSQL_HOST}" -P"${MYSQL_PORT}" -e"${SQL_SCRIPT}")
          command:
            - /bin/sh
      restartPolicy: Never








