// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// GenDatabase is the golang structure of table gen_database for DAO operations like Where/Data.
type GenDatabase struct {
	g.Meta     `orm:"table:gen_database, do:true"`
	Id         interface{} // 编号
	Group      interface{} // 分组名称
	Host       interface{} // 地址
	Port       interface{} // 端口
	User       interface{} // 账号
	Pass       interface{} // 密码
	Name       interface{} // 数据库名称
	Type       interface{} // 数据库类型
	CreateBy   interface{} // 创建者
	CreateTime *gtime.Time // 创建时间
	UpdateBy   interface{} // 更新者
	UpdateTime *gtime.Time // 更新时间
	Remark     interface{} // 备注
}
